### ISSUE TITLE
Error Message returns "XML datatype instance has too many levels of nested nodes. Maximum allowed depth is 128 levels."

### ISSUE THREAD

**Issue by joelax** [erikdarlingdata/DarlingData#196]
@version = '3.33', 
@version_date = '20220701'

I get the error in the subject line whenever I try to use the procs to store data into a table using the agent job. It stores some initial data, but then errors with the above. When I run it to just display results, it works correctly, though I did get the error once. My suspicion is that some XML that's either in the extended event, or perhaps the show plan, is problematic. If there's a version of the PROC that can actually spit out the offending XML I'd be happy to run it to help diagnose the issue.

**Comment by erikdarlingdata** [comment]
Hi @joelax! This has been reported before, but not with a repro so that I could look closer at fixing it. 

Likely, this is in the query plan XML, but I'm unsure if it happens _on insert_ or _on query_ from the XML, e.g. it could happen

```
INSERT
    dbo.x(xml) --Here
SELECT
    x.x.query('.') --Or here
FROM #x;
```
The best thing you can do is run the proc with `@Debug = 1` to get more detail on where it's happening, and what intermediate XML results look like.

Thanks,
Erik

**Comment by erikdarlingdata** [comment]
@joelax I haven't heard back from you in a few months on this, so I'm going to close the issue out for now. If you decide you want to come back to it, let me know.
