### ISSUE TITLE
Log_Hunter additional parameters for not delete record 

### ISSUE THREAD

**Issue by acappelletti** [erikdarlingdata/DarlingData#331]
Hi Erik,
I was analyzing the logs of 2 new servers and I've just started the procedure... I saw that no records regarding **"Login failed**..." were reported, rightly so because they are deleted on line... I'm going by memory at 932. 

Quick solution as I did was to comment out the line and relaunch **LOG_HUNTER,** but if I hadn't looked at the logs materially via SSMS I would have missed that there is some application trying to connect to databases that are not available or in an inaccessible state (let's also say that they are being discontinued).

In any case, someone forgot something on. Hence... 
Do you think it might be of value to insert a parameter like:

- @please_not_delete = 'Login failed for' 
or 
more dramatic @please_bring_all_them_home =   'Login failed for' 

Alen, Italy

**Comment by erikdarlingdata** [comment]
Please use GitHub for support requests.

Thanks,
Erik

From: Alen Cappelletti ***@***.***>
Date: Wednesday, December 6, 2023 at 10:40 AM
To: erikdarlingdata/DarlingData ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [erikdarlingdata/DarlingData] Log_Hunter additional parameters for not delete record (Issue #331)

Hi Erik,
I was analyzing the logs of 2 new servers and I've just started the procedure... I saw that no records regarding "Login failed..." were reported, rightly so because they are deleted on line... I'm going by memory at 932.

Quick solution as I did was to comment out the line and relaunch LOG_HUNTER, but if I hadn't looked at the logs materially via SSMS I would have missed that there is some application trying to connect to databases that are not available or in an inaccessible state (let's also say that they are being discontinued).

In any case, someone forgot something on. Hence...
Do you think it might be of value to insert a parameter like:

  *   @please_not_delete = 'Login failed for'
or
more dramatic @please_bring_all_them_home = 'Login failed for'

Alen, Italy

**Comment by erikdarlingdata** [comment]
I really don't care about this. If you would like to code it, I'll accept a pull request.

Thanks!

**Comment by erikdarlingdata** [comment]
@acappelletti I haven't heard back from you on this, so I'm going to close it out. If you decide you want to work on it, let me know and I'll reopen the issue. Thanks!
