### ISSUE TITLE
SP_humanevents 

### ISSUE THREAD

**Issue by sudhaar** [erikdarlingdata/DarlingData#47]
SP_humanevents failing with below error on SQl server 2012 Always on SP2.
sp_humanevents  @event_type = 'Queries',@seconds_sample = 30;

Error: 
Msg 50000, Level 16, State 1, Procedure sp_HumanEvents, Line 3050 [Batch Start Line 0]

Msg 25623, Level 16, State 3, Line 2
The event action name, "sqlserver.query_hash_signed", is invalid, or the object could not be found

**Comment by erikdarlingdata** [comment]
Yep, the problem is that you're on SQL Server 2012 SP2, which has been out of support for a few years now. If you want to use this proc, you need to[ upgrade to SP4](https://sqlserverupdates.com/sql-server-2012-updates/), which came out back in 2017. 

I can't support unsupported SQL Server versions.

Thanks!

**Comment by sudhaar** [comment]
I agree and I thought the same. Thanks for the update


Thanks,
Sudhakar


Notice: The information contained in this communication, including any attachments, is confidential and is intended only for the use of the recipient(s) named above. If the reader of this message is not an intended recipient, you are notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you receive this communication in error, please notify the sender immediately, and delete the communication, any attachments, and all copies.
