### ISSUE TITLE
Observer Effect on Thread Pool

### ISSUE THREAD

**Issue by netsec4u** [erikdarlingdata/DarlingData#497]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

    @version = '4.9',
    @version_date = '20240915';

**What is the current behavior?**

I've noticed sp_PressureDetector consistantly shows a much higher used thread count than other queries, sometimes as much as double.  It appears the cause for the much higher thread count is the result of the join to sys.dm_resource_governor_workload_groups and the number of threads being used by this DMV to provide the results, hence, the "observer effect."

**If the current behavior is a bug, please provide the steps to reproduce.**

This query is the query that I was using for the comparison.  I have observed this behavior in both a server under production load and a server completely idle.  Although, it is much more obvious in an idle server.

`
SELECT
	MAX(osi.max_workers_count) AS 'TotalThreads'
,	SUM(s.active_Workers_count) AS 'CurrentThreads'
,	MAX(osi.max_workers_count) - SUM(s.active_Workers_count) AS 'AvailableThreads'
,	SUM(s.runnable_tasks_count) AS 'WorkersWaitingForCPU'
,	SUM(s.work_queue_count) AS 'RequestWaitingForThreads'
,	SUM(s.current_workers_count) AS 'CurrentWorkers'
FROM sys.dm_os_Schedulers s
CROSS JOIN sys.dm_os_sys_info AS osi
WHERE status = 'VISIBLE ONLINE';
`

Also, by commenting out the CROSS JOIN for the subquery that references sys.dm_resource_governor_workload_groups and related columns in the SELECT clause results in the thread usage being comparable.

**What is the expected behavior?**

I don't necessarily think this is a bug; however, it raises questions about the validity of the results shown from sp_PressureDetector.  Also, the tool used to identify an issue should not contribute or provide the appearance of contributing to an issue.  But, the value from a single metric should not be used as a cause for an issue either.  I do not know if the better solution is to understand and document the observer effect or to adjust the procedure to make if comparable to the results in the query provided.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

I have reproduced this issue on SQL Server 2017 and 2022.  I have not tried other versions of SQL Server.

**IMPORTANT: If you're going to contribute code, please read the contributing guide first.**
https://github.com/erikdarlingdata/DarlingData/blob/main/CONTRIBUTING.md

**Comment by erikdarlingdata** [comment]
Thanks for digging in on this! I’m at PASS this week, but it’ll get my attention when I’m back home.


From: Robert Eder ***@***.***>
Date: Monday, November 4, 2024 at 11:34 AM
To: erikdarlingdata/DarlingData ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [erikdarlingdata/DarlingData] Observer Effect on Thread Pool (Issue #497)

Version of the script
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

@version = '4.9',

@version_date = '20240915';

What is the current behavior?

I've noticed sp_PressureDetector consistantly shows a much higher used thread count than other queries, sometimes as much as double. It appears the cause for the much higher thread count is the result of the join to sys.dm_resource_governor_workload_groups and the number of threads being used by this DMV to provide the results, hence, the "observer effect."

If the current behavior is a bug, please provide the steps to reproduce.

This query is the query that I was using for the comparison. I have observed this behavior in both a server under production load and a server completely idle. Although, it is much more obvious in an idle server.

SELECT MAX(osi.max_workers_count) AS 'TotalThreads' , SUM(s.active_Workers_count) AS 'CurrentThreads' , MAX(osi.max_workers_count) - SUM(s.active_Workers_count) AS 'AvailableThreads' , SUM(s.runnable_tasks_count) AS 'WorkersWaitingForCPU' , SUM(s.work_queue_count) AS 'RequestWaitingForThreads' , SUM(s.current_workers_count) AS 'CurrentWorkers' FROM sys.dm_os_Schedulers s CROSS JOIN sys.dm_os_sys_info AS osi WHERE status = 'VISIBLE ONLINE';

Also, by commenting out the CROSS JOIN for the subquery that references sys.dm_resource_governor_workload_groups and related columns in the SELECT clause results in the thread usage being comparable.

What is the expected behavior?

I don't necessarily think this is a bug; however, it raises questions about the validity of the results shown from sp_PressureDetector. Also, the tool used to identify an issue should not contribute or provide the appearance of contributing to an issue. But, the value from a single metric should not be used as a cause for an issue either. I do not know if the better solution is to understand and document the observer effect or to adjust the procedure to make if comparable to the results in the query provided.

Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?

I have reproduced this issue on SQL Server 2017 and 2022. I have not tried other versions of SQL Server.

IMPORTANT: If you're going to contribute code, please read the contributing guide first.
https://github.com/erikdarlingdata/DarlingData/blob/main/CONTRIBUTING.md

**Comment by erikdarlingdata** [comment]
@netsec4u can you be a little more clear about the issue you're seeing? perhaps with a screenshot? I can't find a difference in query results between the standalone query you sent and the PressureDetector results. I've been messing with it with and without a workload running.

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/58d56578-f564-4431-a55c-c28a331f22f5">

**Comment by netsec4u** [comment]
Here is a SQL 2022 instance under no load:

![image](https://github.com/user-attachments/assets/cfd12d94-f00b-4c6b-8834-fadf31da2de6)

Here is a SQL 2012 instance under load:

![image](https://github.com/user-attachments/assets/e902c5e8-85ae-498b-beab-d5ddcc49ccdf)

I took the query starting at line 2501 and put it into a query window.  Then pasted again and commented the subquery aliased as 
"wg"  Below is the execution of the three queryes.

![image](https://github.com/user-attachments/assets/b0d602a1-829e-4849-b4d3-b2443748e653)

Here are the three queries.

```sql
SELECT MAX(osi.max_workers_count) AS 'TotalThreads' ,	SUM(s.active_Workers_count) AS 'CurrentThreads' ,	MAX(osi.max_workers_count) - SUM(s.active_Workers_count) AS 'AvailableThreads' ,	SUM(s.runnable_tasks_count) AS 'WorkersWaitingForCPU' ,	SUM(s.work_queue_count) AS 'RequestWaitingForThreads' ,	SUM(s.current_workers_count) AS 'CurrentWorkers' FROM sys.dm_os_Schedulers s CROSS JOIN sys.dm_os_sys_info AS osi WHERE status = 'VISIBLE ONLINE';

        SELECT
            total_threads =
                MAX(osi.max_workers_count),
            used_threads =
                SUM(dos.active_workers_count),
            available_threads =
                MAX(osi.max_workers_count) - SUM(dos.active_workers_count),
            reserved_worker_count = 0,
            threads_waiting_for_cpu =
                SUM(dos.runnable_tasks_count),
            requests_waiting_for_threads =
                SUM(dos.work_queue_count),
            current_workers =
                SUM(dos.current_workers_count),
            total_active_request_count =
                MAX(wg.active_request_count),
            total_queued_request_count =
                MAX(wg.queued_request_count),
            total_blocked_task_count =
                MAX(wg.blocked_task_count),
            total_active_parallel_thread_count =
                MAX(wg.active_parallel_thread_count),
            avg_runnable_tasks_count =
                AVG(dos.runnable_tasks_count),
            high_runnable_percent =
                MAX(ISNULL(r.high_runnable_percent, 0))
        FROM sys.dm_os_schedulers AS dos
        CROSS JOIN sys.dm_os_sys_info AS osi
        CROSS JOIN
        (
            SELECT
                wg.active_request_count,
                wg.queued_request_count,
                wg.blocked_task_count,
                wg.active_parallel_thread_count
            FROM sys.dm_resource_governor_workload_groups AS wg
        ) AS wg
        OUTER APPLY
        (
            SELECT
                high_runnable_percent =
                    '' +
                    RTRIM(y.runnable_pct) +
                    '% of ' +
                    RTRIM(y.total) +
                    ' queries are waiting to get on a CPU.'
            FROM
            (
                SELECT
                    x.total,
                    x.runnable,
                    runnable_pct =
                        CONVERT
                        (
                            decimal(38,2),
                            (
                                x.runnable / (1. * NULLIF(x.total, 0))
                            )
                        ) * 100.
                FROM
                (
                    SELECT
                        total =
                            COUNT_BIG(*),
                        runnable =
                            SUM
                            (
                                CASE
                                    WHEN der.status = N'runnable'
                                    THEN 1
                                    ELSE 0
                                END
                            )
                    FROM sys.dm_exec_requests AS der
                    WHERE der.session_id > 50
                ) AS x
            ) AS y
            WHERE y.runnable_pct >= 10
            AND   y.total >= 4
        ) AS r
        WHERE dos.status = N'VISIBLE ONLINE'
        OPTION(MAXDOP 1, RECOMPILE);


        SELECT
            total_threads =
                MAX(osi.max_workers_count),
            used_threads =
                SUM(dos.active_workers_count),
            available_threads =
                MAX(osi.max_workers_count) - SUM(dos.active_workers_count),
            reserved_worker_count = 0,
            threads_waiting_for_cpu =
                SUM(dos.runnable_tasks_count),
            requests_waiting_for_threads =
                SUM(dos.work_queue_count),
            current_workers =
                SUM(dos.current_workers_count),
/*
            total_active_request_count =
                MAX(wg.active_request_count),
            total_queued_request_count =
                MAX(wg.queued_request_count),
            total_blocked_task_count =
                MAX(wg.blocked_task_count),
            total_active_parallel_thread_count =
                MAX(wg.active_parallel_thread_count),
*/
            avg_runnable_tasks_count =
                AVG(dos.runnable_tasks_count),
            high_runnable_percent =
                MAX(ISNULL(r.high_runnable_percent, 0))
        FROM sys.dm_os_schedulers AS dos
        CROSS JOIN sys.dm_os_sys_info AS osi
/*
        CROSS JOIN
        (
            SELECT
                wg.active_request_count,
                wg.queued_request_count,
                wg.blocked_task_count,
                wg.active_parallel_thread_count
            FROM sys.dm_resource_governor_workload_groups AS wg
        ) AS wg
*/
        OUTER APPLY
        (
            SELECT
                high_runnable_percent =
                    '' +
                    RTRIM(y.runnable_pct) +
                    '% of ' +
                    RTRIM(y.total) +
                    ' queries are waiting to get on a CPU.'
            FROM
            (
                SELECT
                    x.total,
                    x.runnable,
                    runnable_pct =
                        CONVERT
                        (
                            decimal(38,2),
                            (
                                x.runnable / (1. * NULLIF(x.total, 0))
                            )
                        ) * 100.
                FROM
                (
                    SELECT
                        total =
                            COUNT_BIG(*),
                        runnable =
                            SUM
                            (
                                CASE
                                    WHEN der.status = N'runnable'
                                    THEN 1
                                    ELSE 0
                                END
                            )
                    FROM sys.dm_exec_requests AS der
                    WHERE der.session_id > 50
                ) AS x
            ) AS y
            WHERE y.runnable_pct >= 10
            AND   y.total >= 4
        ) AS r
        WHERE dos.status = N'VISIBLE ONLINE'
        OPTION(MAXDOP 1, RECOMPILE);
```

**Comment by erikdarlingdata** [comment]
@netsec4u make sure you’ve updated PressureDetector. Those queries changed a couple/few weeks ago. I haven’t bumped version/date because I haven’t done an official release yet (waiting to get some stuff into QuickieStore).

**Comment by netsec4u** [comment]
Ah.  The new version does not have this issue.  Thanks!
