### ISSUE TITLE
Azure SQL Database

### ISSUE THREAD

**Issue by pricewise987** [erikdarlingdata/DarlingData#58]
**Which script is your question about?**

**sp_PressureDetector**

Attached is an Azure SQL Database Compatible Version of sp_PressureDetector.

[sp_PressureDetector.txt](https://github.com/erikdarlingdata/DarlingData/files/4789315/sp_PressureDetector.txt)

If you comment out the "DAC-enabled" check it works perfectly.

Thanks again for these Erik - brilliant scripts to have.

**Comment by erikdarlingdata** [comment]
I need to be very honest with you about this, but I want you to know that there's no meanness in anything I'm saying. I appreciate people using these scripts, and taking the time to try to improve upon them. But the thing here is that this doesn't really make an improvement. 

Lemme explain why:

You've sent me a text file, not a pull request, with a bit of code that I want in there quoted out. I really don't want to have an "Azure branch" of this code with a section quoted out or deleted, because later if I make any changes, I have to remember to make them in two places. In other words, it's not a tenable situation for me as the maintainer of these scripts. It creates more work for me long term.

If you want to see an example of a good submission via pull request to get things cloud compatible, check out #57. It respects the differences between on-prem, Managed Instances, and Azure SQL DB, and it doesn't do it by just removing the parts that don't work in different places. It's handled dynamically like other parts of this script are, to conform with differences across SQL Server versions over time. You can see how I handle columns being present in some versions and not others. 

Of course, if you want to write code like that (you can even copy bits from the pull request I linked to), I'd be happy to have it. You can also choose not to, and continue to use the script with parts quoted out that don't work for you. When new versions come out, you'll need to remember to remove that part again, but that's pretty minor. 

I respect that learning stuff like GitHub can be confusing and time consuming, and you just might not have the resources to learn how to write code and [create pull requests](https://www.brentozar.com/archive/2018/01/peoples-githubs-fork-clone-pull/). Likewise, I don't have cloud SQL Server versions to test the changes and write them on my own. 

Another alternative, assuming doing the coding yourself isn't in the cards, would be to open an issue here, and maybe someone with the right setup will come along and work on it. Feel free to open new issue for that, and I'll leave it open for a while. 

Thanks,
Erik
